### PR TITLE
Update eval_surv.py for pandas 2.0

### PR DESCRIPTION
**Pull request by hminle**
Changed `pd.Series.is_monotonic` to `pd.Series.is_monotonic_increasing` for newer versions of pandas.

### CODE REVIEW

**Review by sheisnt4046 — APPROVED** [review]
This change works for 

> attributeerror: 'series' object has no attribute 'is_monotonic'

in a newer version Pandas.

**Comment by shi-ang** [comment]
Also, change `iteritems` to `items` for pandas 2.0.0+

**Comment by nilskre** [comment]
Hi all,
after stumbling across exactly this issue #162, I found this PR, which fixes the issue. Therefore, I just wanted to ask if there are any plans to merge this?
Thanks in advance!

**Comment by antonromashko** [comment]
@havakv Hi, please take a look at this PR. It's still relevant for many.

**Comment by havakv** [comment]
I'm not really maintaining this anymore, so if anyone wants to take over pleas just make a fork. However, I've tried to make this work, but needed to make a some other changes. So @hminle or @antonromashko (or anyone else), let me know if https://github.com/havakv/pycox/pull/180 works for you

**Comment by havakv** [comment]
Closed in preference for #180

**Pull request closed without merging**
